# Generated by Django 4.1.5 on 2023-02-03 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expire_datetime', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                (
                    'quiz',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='players', to='quiz.quiz'
                    ),
                ),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ('quiz', '-score', 'user__last_name', 'user__first_name'),
                'unique_together': {('quiz', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('LEADING_ACTOR', 'Actor in a Leading Role'),
                            ('SUPPORTING_ACTOR', 'Actor in a Supporting Role'),
                            ('LEADING_ACTRESS', 'Actress in a Leading Role'),
                            ('SUPPORTING_ACTRESS', 'Actress in a Supporting Role'),
                            ('ANIMATED_FEATURE_FILM', 'Animated Feature Film'),
                            ('ANIMATED_SHORT_FILM', 'Animated Short Film'),
                            ('BEST_PICTURE', 'Best Picture'),
                            ('CINEMATOGRAPHY', 'Cinematography'),
                            ('COSTUME_DESIGN', 'Costume Design'),
                            ('DIRECTING', 'Directing'),
                            ('DOCUMENTARY_FEATURE', 'Documentary (Feature)'),
                            ('DOCUMENTARY_SHORT_SUBJECT', 'Documentary (Short Subject)'),
                            ('FILM_EDITING', 'Film Editing'),
                            ('FOREIGN_LANGUAGE_FILM', 'Foreign Language Film'),
                            ('LIVE_ACTION_SHORT_FILM', 'Live Action Short Film'),
                            ('MAKEUP_AND_HAIRSTYLING', 'Makeup and Hairstyling'),
                            ('MUSIC_ORIGINAL_SCORE', 'Music (Original Score)'),
                            ('MUSIC_ORIGINAL_SONG', 'Music (Original Song)'),
                            ('PRODUCTION_DESIGN', 'Production Design'),
                            ('SOUND_EDITING', 'Sound Editing'),
                            ('SOUND_MIXING', 'Sound Mixing'),
                            ('VISUAL_EFFECTS', 'Visual Effects'),
                            ('WRITING_ADAPTED_SCREENPLAY', 'Writing (Adapted Screenplay)'),
                            ('WRITING_ORIGINAL_SCREENPLAY', 'Writing (Original Screenplay)'),
                        ],
                        max_length=255,
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('is_winner', models.BooleanField(default=False)),
                (
                    'quiz',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='quiz.quiz'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Nominee',
                'verbose_name_plural': 'Nominees',
                'ordering': ('name',),
                'unique_together': {('quiz', 'category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'nominee',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='nominee_answers',
                        to='quiz.nominee',
                    ),
                ),
                (
                    'player',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='anwers', to='quiz.player'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ('player__user__last_name', 'player__user__first_name', 'nominee__category'),
                'unique_together': {('player', 'nominee')},
            },
        ),
    ]
