# Generated by Django 2.0.2 on 2018-03-04 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('player__name', 'nominee__category'),
            },
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('LEADING_ACTOR', 'Actor in a Leading Role'), ('SUPPORTING_ACTOR', 'Actor in a Supporting Role'), ('LEADING_ACTRESS', 'Actress in a Leading Role'), ('SUPPORTING_ACTRESS', 'Actress in a Supporting Role'), ('ANIMATED_FEATURE_FILM', 'Animated Feature Film'), ('ANIMATED_SHORT_FILM', 'Animated Short Film'), ('BEST_PICTURE', 'Best Picture'), ('CINEMATOGRAPHY', 'Cinematography'), ('COSTUME_DESIGN', 'Costume Design'), ('DIRECTING', 'Directing'), ('DOCUMENTARY_FEATURE', 'Documentary (Feature)'), ('DOCUMENTARY_SHORT_SUBJECT', 'Documentary (Short Subject)'), ('FILM_EDITING', 'Film Editing'), ('FOREIGN_LANGUAGE_FILM', 'Foreign Language Film'), ('LIVE_ACTION_SHORT_FILM', 'Live Action Short Film'), ('MAKEUP_AND_HAIRSTYLING', 'Makeup and Hairstyling'), ('MUSIC_ORIGINAL_SCORE', 'Music (Original Score)'), ('MUSIC_ORIGINAL_SONG', 'Music (Original Song)'), ('PRODUCTION_DESIGN', 'Production Design'), ('SOUND_EDITING', 'Sound Editing'), ('SOUND_MIXING', 'Sound Mixing'), ('VISUAL_EFFECTS', 'Visual Effects'), ('WRITING_ADAPTED_SCREENPLAY', 'Writing (Adapted Screenplay)'), ('WRITING_ORIGINAL_SCREENPLAY', 'Writing (Original Screenplay)')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('is_winner', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expire_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_qp', to='oscarquiz.Player')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_qp', to='oscarquiz.Quiz')),
            ],
            options={
                'ordering': ('quiz__name', 'player__name'),
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='players',
            field=models.ManyToManyField(through='oscarquiz.QuizPlayer', to='oscarquiz.Player'),
        ),
        migrations.AddField(
            model_name='nominee',
            name='oscar_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oscarquiz.Quiz'),
        ),
        migrations.AddField(
            model_name='answer',
            name='nominee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominee_answers', to='oscarquiz.Nominee'),
        ),
        migrations.AddField(
            model_name='answer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_anwers', to='oscarquiz.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='quizplayer',
            unique_together={('quiz', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='nominee',
            unique_together={('oscar_quiz', 'category', 'name')},
        ),
    ]
