# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oscarquiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='nominee',
            name='nominee_type',
        ),
        migrations.DeleteModel(
            name='NomineeType',
        ),
    ]
