# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscarquiz', '0002_auto_20170225_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('name',), 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AddField(
            model_name='nominee',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
    ]
