# Generated by Django 2.1.7 on 2019-02-24 13:05

from django.db import migrations, models


def set_category(apps, schema_editor):
    Answer = apps.get_model("oscarquiz", "Answer")

    for answer in Answer.objects.all():
        answer.category = answer.nominee.category
        answer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('oscarquiz', '0002_quizplayer_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='category',
            field=models.CharField(blank=True, choices=[('LEADING_ACTOR', 'Actor in a Leading Role'), ('SUPPORTING_ACTOR', 'Actor in a Supporting Role'), ('LEADING_ACTRESS', 'Actress in a Leading Role'), ('SUPPORTING_ACTRESS', 'Actress in a Supporting Role'), ('ANIMATED_FEATURE_FILM', 'Animated Feature Film'), ('ANIMATED_SHORT_FILM', 'Animated Short Film'), ('BEST_PICTURE', 'Best Picture'), ('CINEMATOGRAPHY', 'Cinematography'), ('COSTUME_DESIGN', 'Costume Design'), ('DIRECTING', 'Directing'), ('DOCUMENTARY_FEATURE', 'Documentary (Feature)'), ('DOCUMENTARY_SHORT_SUBJECT', 'Documentary (Short Subject)'), ('FILM_EDITING', 'Film Editing'), ('FOREIGN_LANGUAGE_FILM', 'Foreign Language Film'), ('LIVE_ACTION_SHORT_FILM', 'Live Action Short Film'), ('MAKEUP_AND_HAIRSTYLING', 'Makeup and Hairstyling'), ('MUSIC_ORIGINAL_SCORE', 'Music (Original Score)'), ('MUSIC_ORIGINAL_SONG', 'Music (Original Song)'), ('PRODUCTION_DESIGN', 'Production Design'), ('SOUND_EDITING', 'Sound Editing'), ('SOUND_MIXING', 'Sound Mixing'), ('VISUAL_EFFECTS', 'Visual Effects'), ('WRITING_ADAPTED_SCREENPLAY', 'Writing (Adapted Screenplay)'), ('WRITING_ORIGINAL_SCREENPLAY', 'Writing (Original Screenplay)')], max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('player', 'category')},
        ),
        migrations.RunPython(set_category),
        migrations.AlterField(
            model_name='answer',
            name='category',
            field=models.CharField(choices=[('LEADING_ACTOR', 'Actor in a Leading Role'), ('SUPPORTING_ACTOR', 'Actor in a Supporting Role'), ('LEADING_ACTRESS', 'Actress in a Leading Role'), ('SUPPORTING_ACTRESS', 'Actress in a Supporting Role'), ('ANIMATED_FEATURE_FILM', 'Animated Feature Film'), ('ANIMATED_SHORT_FILM', 'Animated Short Film'), ('BEST_PICTURE', 'Best Picture'), ('CINEMATOGRAPHY', 'Cinematography'), ('COSTUME_DESIGN', 'Costume Design'), ('DIRECTING', 'Directing'), ('DOCUMENTARY_FEATURE', 'Documentary (Feature)'), ('DOCUMENTARY_SHORT_SUBJECT', 'Documentary (Short Subject)'), ('FILM_EDITING', 'Film Editing'), ('FOREIGN_LANGUAGE_FILM', 'Foreign Language Film'), ('LIVE_ACTION_SHORT_FILM', 'Live Action Short Film'), ('MAKEUP_AND_HAIRSTYLING', 'Makeup and Hairstyling'), ('MUSIC_ORIGINAL_SCORE', 'Music (Original Score)'), ('MUSIC_ORIGINAL_SONG', 'Music (Original Song)'), ('PRODUCTION_DESIGN', 'Production Design'), ('SOUND_EDITING', 'Sound Editing'), ('SOUND_MIXING', 'Sound Mixing'), ('VISUAL_EFFECTS', 'Visual Effects'), ('WRITING_ADAPTED_SCREENPLAY', 'Writing (Adapted Screenplay)'), ('WRITING_ORIGINAL_SCREENPLAY', 'Writing (Original Screenplay)')], max_length=255),
        ),
    ]
