# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oscarquiz', '0003_auto_20170225_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='oscarquiz.Category'),
        ),
    ]
