# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oscarquiz', '0004_auto_20170225_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='nominee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominee_answers', to='oscarquiz.Nominee'),
        ),
    ]
