# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oscarquiz', '0005_auto_20170225_2301'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([]),
        ),
    ]
